template-file-path: root-stack.yml
parameters:
  CFNTemplatesBucket: photo-uploader-cfn-templates-825765391206
  CreateOIDCProvider: 'false'
  DBPassword: '****'
  GitHubOrg: peprah12git
  DBName: photouploader
  GitHubRepo: Photo-uploader
  DBUsername: adminuser
tags: {}
