template-file-path: root-stack.yml
parameters:
  GitHubOrg: peprah12git
  GitHubRepo: photo-uploader
  DBName: photouploader
  DBUsername: adminuser
  DBPassword: "{{resolve:secretsmanager:/photo-uploader/db/password:SecretString:password}}"
  CFNTemplatesBucket: photo-uploader-cfn-templates-885703011275
  CreateOIDCProvider: 'true'
tags:
  Project: photo-uploader
  ManagedBy: CloudFormation
  Environment: production