template-file-path: root-stack.yml
parameters:
  GitHubOrg: peprah12git
  GitHubRepo: photo-uploader
  DBName: photouploader
  DBUsername: adminuser
  DBPassword: "{{resolve:ssm-secure:/photo-uploader/db/password}}"
  CFNTemplatesBucket: photo-uploader-cfn-templates-904233109505
tags:
  Project: photo-uploader
  ManagedBy: CloudFormation
  Environment: production