AWSTemplateFormatVersion: '2010-09-09'
Description: ECR Repository for Photo Uploader

Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
#    DeletionPolicy: Retain
    Properties:
      RepositoryName: photo-uploader
      ImageScanningConfiguration:
        ScanOnPush: true
      ImageTagMutability: MUTABLE
      EncryptionConfiguration:
        EncryptionType: AES256
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last 10 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 10
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
      Tags:
        - Key: Project
          Value: photo-uploader
        - Key: Environment
          Value: production
        - Key: ManagedBy
          Value: CloudFormation

Outputs:
  ECRRepositoryUri:
    Description: ECR Repository URI
    Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/photo-uploader"
    Export:
      Name: photo-uploader-ECRRepositoryUri

  ECRRepositoryName:
    Description: ECR Repository Name
    Value: !Ref ECRRepository
    Export:
      Name: photo-uploader-ECRRepositoryName